Blog/Models/HomeViewModels/AuthorViewModel.cs
using PagedList.Core;

namespace Blog.Models.HomeViewModels
{
    public class AuthorViewModel
    {
        public ApplicationUser Author { get; set; }
        public IPagedList<BlogModel> Blogs { get; set; }
        public string SearchString { get; set; }
        public int PageNumber { get; set; }
    }
}

Blog/Controllers/BlogController.cs
using Blog.BusinessManagers.Interfaces;
using Blog.Models.Blog;
using Blog.Models.BlogViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Blog.Controllers
{
    [Authorize]
    public class BlogController : Controller
    {
        private readonly IBlogBusinessManager _blogBusinessManager;

        public BlogController(IBlogBusinessManager blogBusinessManager)
        {
            _blogBusinessManager = blogBusinessManager;
        }

        [AllowAnonymous]
        [Route("Post/{id}")]
        public async Task<IActionResult> Index(int? id)
        {
            var actionResult = await _blogBusinessManager.GetBlogViewModel(id, User);

            if (actionResult.Result is null)
                return View(actionResult.Value);

            return actionResult.Result;
        }

        public IActionResult Create()
        {
            return View(new CreateViewModel());
        }

        public async Task<IActionResult> Edit(int? id)
        {
            var actionResult = await _blogBusinessManager.GetEditViewModel(id, User);

            if (actionResult.Result is null)
                return View(actionResult.Value);

            return actionResult.Result;
        }


        [HttpPost]
        public async Task<IActionResult> Add(CreateViewModel createViewModel)
        {
            await _blogBusinessManager.CreateBlog(createViewModel, User);
            return RedirectToAction("Index", "Admin");
        }

        [HttpPost]
        public async Task<IActionResult> Update(EditViewModel editViewModel)
        {
            var actionResult = await _blogBusinessManager.UpdateBlog(editViewModel, User);

            if (actionResult.Result is null)
                return RedirectToAction("Edit", new { editViewModel.Blog.Id });

            return actionResult.Result;
        }
    }
}

Blog/Controllers/HomeController.cs
using Blog.BusinessManagers.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    public class HomeController : Controller
    {
        private readonly IBlogBusinessManager _blogBusinessManager;
        private readonly IHomeBusinessManager _homeBusinessManager;

        public HomeController(IBlogBusinessManager blogBusinessManager,IHomeBusinessManager homeBusinessManager)
        {
            _blogBusinessManager = blogBusinessManager;
            _homeBusinessManager = homeBusinessManager;
        }

        public IActionResult Index(string searchString,int? page)
        {
            return View(_blogBusinessManager.GetIndexViewModel(searchString, page));
        }

        public IActionResult Author(string authorId,string searchString,int? page)
        {
            var actionResult = _homeBusinessManager.GetAuthorViewModel(authorId, searchString, page);
            if (actionResult.Result is null)
                return View(actionResult.Value);

            return actionResult.Result;
        }


    }
}

Blog/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Blog.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(); });
        }
    }
}

Blog/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Blog.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(); });
        }
    }
}

Blog/ViewComponents/NavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Blog.ViewComponents
{
    public class NavigationViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(); });
        }
    }
}

Blog/Views/Home/Author.cshtml
@model Blog.Models.HomeViewModels.AuthorViewModel
@using PagedList.Core.Mvc
@{
    Layout = "_HomeLayout";
    ViewData["HeaderImage"] = $"../../UserFiles/Users/{Model.Author.Id}/HeaderImage.jpg";
    ViewData["HeaderTitle"] = $"{Model.Author.FirstName} {Model.Author.LastName}";
    ViewData["SubHeader"] = Model.Author.SubHeader;
}

<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                @Html.Raw(Model.Author.AboutContent)
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <form asp-controller="Home" asp-action="Author" class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                    <div class="input-group mb-3">
                        <input name="AuthorId" hidden readonly value="@Model.Author.Id" />
                        <input asp-for="SearchString" type="text" class="form-control" placeholder="Search posts for...." />
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" style="padding:0 10px 0 10px">Search</button>
                        </div>
                    </div>
                </form>
                <div class="row align-content-center">
                    @foreach (var blog in Model.Blogs)
                    {
                        <div class="col-lg-4 col-md-3 mb-4">
                            <div class="card border-0 shadow">
                                <img src="~/UserFiles/Blogs/@blog.Id/HeaderImage.jpg" class="card-img-top" />
                                <div class="card-body">
                                    <div class="row text-center" style="margin:0px auto 10px 0px;">
                                        <h5 class="card-title text-center w-100">
                                            <a asp-controller="Blog" asp-action="Index" asp-route-id="@blog.Id">
                                                @blog.Title
                                            </a>
                                        </h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <div list="@Model.Blogs" count="20">
                    <pager class="pager-container" list="@Model.Blogs" options="@PagedListRenderOptions.Bootstrap4PageNumbersPlusPrevAndNext" asp-action="Index" asp-controller="Home" asp-route-query="@Model.SearchString" />
                </div>
            </div>
        </div>
    </div>
</article>

Blog/Views/Home/Index.cshtml
@model Blog.Models.HomeViewModels.IndexViewModel
@using PagedList.Core.Mvc

@{ 
    ViewData["Title"] = "Kinawy's Blog";
}


<div class="container">
    <form asp-controller="Home" asp-action="Index" class="d-none d-md-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group mb-3">
            <input asp-for="SearchString" class="form-control" placeholder="Search blogs for...." />
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" style="padding:0 10px 0 10px">Search</button>
            </div>
        </div>
    </form>
    <div class="row align-content-center">
        @foreach (var blog in Model.Blogs)
        {
            <div class="col-lg-4 col-md-3 mb-4">
                <div class="card border-0 shadow">
                    <img src="~/UserFiles/Blogs/@blog.Id/HeaderImage.jpg" class="card-img-top" />
                    <div class="card-body">
                        <div class="row text-center" style="margin:0px auto 10px 0px">
                            <h5 class="card-title text-center w-100"><a asp-controller="Blog" asp-action="Index" asp-route-id="@blog.Id">@blog.Title</a></h5>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    <div list="@Model.Blogs" count="20">
        <pager class="pager-container" list="@Model.Blogs" options="@PagedListRenderOptions.Bootstrap4PageNumbersPlusPrevAndNext" asp-action="Index" asp-controller="Home" asp-route-query="@Model.SearchString" />
    </div>
</div>

Blog/Views/Home/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"]</title>

    <!-- Bootstrap core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="~/css/clean-blog.min.css" rel="stylesheet">
</head>
<body>
    
    @await Component.InvokeAsync("Navigation")


    @await Component.InvokeAsync("Header")

    <div class="content">
        @RenderBody()
    </div>


    @await Component.InvokeAsync("Footer")


    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="~/js/clean-blog.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>